version: '3'
services:
  node:
    restart: always
    image: nodejs-web-app:${IMAGE_TAG}
    ports:
      - 8084:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo7:/data/db
volumes:
 mongo7:


#  sudo /etc/init.d/mongodb stop