name: Check Label

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled
      - reopened
      - synchronize

jobs:
  fail-for-draft:
    if: contains(github.event.pull_request.labels.*.name, 'hold') || contains(github.event.pull_request.labels.*.name, 'draft')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is a draft/hold
        run: |
          echo "This PR is currently a draft/hold"
          exit 1
